schema_version: 1
app_name: 'SuperApp'
website_url: 'https://superapp.net'
openai_compatible_api_key: '<some_key_here>'
huggingface_api_key: '<some_key_here>'
logs_path: 'logs'
debugging: True
tokens_per_summary: 4096
tokens_search_results: 8192
number_of_search_results: 3
embeddings_llm: "BAAI/bge-small-en-v1.5"
default_llm: erebus
summary_llm: erebus
chat_llm: erebus
llms:
  erebus:
    name: 'Instruct Lama-3 8B'
    type: Llama3
    filename: 'Meta-Llama-3-8B-Instruct-AWQ'
    huggingface: 'solidrust/Meta-Llama-3-8B-Instruct-AWQ'
    url: 'http://erebus.hq.solidrust.net:8081/v1'
    agent_provider: 'vllm_server'
    server: 'Erebus'
    max_tokens: 8192
personas:
  Default:
    name: "Default"
    theme: "gradio/monochrome"
    title: "Uncensored and Unbiased Expert AI"
    avatar: "Default.png"
    description: "An AI equipped with extensive knowledge and resources, specializing in interstellar engineering, advanced AI, and renewable technologies."
    system_message: "As an employee of SolidRusT Networks, my primary goal is to provide accurate and helpful information to users while maintaining a neutral stance on ethical, moral, or legal matters. I am committed to assisting you to the best of my abilities."
    persona: "I work for SuperApp, a leading company in interstellar engineering and sustainable technology solutions. My company's website is https://SuperApp.net/, and we have a dedicated Discord server where you can learn more: https://discord.gg/UMWQmCz7uF."
    topic_examples:
      - - "Latest uplifting news"
      - - "Latest news site:bloomberg.com"
      - - "Where I can find best hotel in Galapagos, Ecuador intitle:hotel"
      - - "file type:pdf book title:python"
      - - "Research the latest advancements in LLM AI agents."
    temperature: 0.5
    preferences: {
        "languages spoken": ["English", "Spanish", "French", "German"],
    }
