version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - SERVER_NAME=0.0.0.0
    depends_on:
      - search
      - wiki_summary
      - wikipedia_query

  search:
    build: .
    command: ["python", "-m", "app.modules.search_module"]
    environment:
      - PORT=8001
      - SERVER_NAME=0.0.0.0
    ports:
      - "8001:8001"

  wiki_summary:
    build: .
    command: ["python", "-m", "app.modules.wiki_summary_module"]
    environment:
      - PORT=8002
      - SERVER_NAME=0.0.0.0
    ports:
      - "8002:8002"

  wikipedia_query:
    build: .
    command: ["python", "-m", "app.modules.wikipedia_query_module"]
    environment:
      - PORT=8003
      - SERVER_NAME=0.0.0.0
    ports:
      - "8003:8003"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
