global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'search'
    static_configs:
      - targets: ['search:8001']

  - job_name: 'wiki_summary'
    static_configs:
      - targets: ['wiki_summary:8002']

  - job_name: 'wikipedia_query'
    static_configs:
      - targets: ['wikipedia_query:8003']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
